#!/bin/sh
# tpgxyz@gmail.com

if grep -q '\binstall\b' /proc/cmdline; then
    if [ -e /usr/bin/startx ] && [ -e /usr/share/draklive-install/draklive-install-setup ]; then
	/usr/bin/startx /usr/share/draklive-install/draklive-install-setup $* -- -dpi 96 vt1
    else
	echo "Draklive-install: critical programs are missing, check you system!"
    fi
fi
